// KPI feature module barrel export
export {
  useKPIRecords,
  useAllocationConfig,
  useAllocationPeriods,
  useCreateAllocationPeriod,
  useCalculateAllocation,
  useApproveAllocation,
  useDeleteAllocationPeriod,
  useDeptBudgetAllocations,
  useUpsertDeptBudgetAllocation,
  useDeleteDeptBudgetAllocation,
  useFundSummary,
  useEmployeeBonus,
  useAllocationCycle,
  useUpdateAllocationCycle,
  useCalculateBonus,
  useSalaryRecords,
  useCreateSalaryBatch,
  useSalaryDeductions,
  useAcceptanceRounds,
  useUpsertAcceptanceRound,
  useDeleteAcceptanceRound,
  kpiKeys,
} from './hooks/use-kpi';
